apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: jh1qi1cx7-python
  janus-idp.io/tekton: jh1qi1cx7-python
  backstage.io/kubernetes-id: jh1qi1cx7-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: jh1qi1cx7-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
